title: "Интерактивный редактор сайта"
description: "Сайт с переключением темы и редактируемым контентом"
baseurl: ""
url: "https://yourusername.github.io" # замените yourusername на ваш

# Базовые настройки Jekyll
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройки для безопасности
safe: true
whitelist:
  - jekyll-feed
  - jekyll-seo-tag

# Исключения
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .github/

# Настройки сборки
future: true
timezone: Europe/Moscow

# Кастомные настройки
author: "Ваше Имя"
email: "your-email@example.com"
default_theme: "light"

# Настройки для GitHub Pages
repository: "yourusername/yourusername.github.io" # замените на ваш
