title: "Интерактивный редактор сайта"
description: "Сайт с переключением темы и редактируемым контентом"
baseurl: ""
url: "https://yourusername.github.io"
github_username: yourusername

# Настройки Jekyll
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Кастомные настройки
author: "Ваше Имя"
email: "your-email@example.com"
default_theme: "light"

# Настройки для GitHub Pages
repository: "yourusername/yourusername.github.io"
safe: true
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Настройки доступа
view_mode: true
